### PR TITLE
Set the correct service for span

### PR DESCRIPTION
**Pull request by icebob**

### CODE REVIEW

**Comment by iatzmon** [comment]
@icebob adding the service property seems to be causing a problem with the Jaeger exporter, I'm getting this response when running a query:
```{
  "error": {
    "errors": [
      {
        "message": "Maximum call stack size exceeded",
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
          "exception": {
            "stacktrace": [
              "RangeError: Maximum call stack size exceeded",
              "    at Function.keys (<anonymous>)",
              "    at JaegerTraceExporter.flattenTags (/Users/itamar/dev/backend/deep-knowledge/node_modules/moleculer/src/tracing/exporters/base.js:80:17)",
              "    at Object.keys.reduce (/Users/itamar/dev/backend/deep-knowledge/node_modules/moleculer/src/tracing/exporters/base.js:85:29)",
              "    at Array.reduce (<anonymous>)",
              "    at JaegerTraceExporter.flattenTags (/Users/itamar/dev/backend/deep-knowledge/node_modules/moleculer/src/tracing/exporters/base.js:80:27)",
              "    at Object.keys.reduce (/Users/itamar/dev/backend/deep-knowledge/node_modules/moleculer/src/tracing/exporters/base.js:85:29)",
              "    at Array.reduce (<anonymous>)",
              "    at JaegerTraceExporter.flattenTags (/Users/itamar/dev/backend/deep-knowledge/node_modules/moleculer/src/tracing/exporters/base.js:80:27)",
              "    at Object.keys.reduce (/Users/itamar/dev/backend/deep-knowledge/node_modules/moleculer/src/tracing/exporters/base.js:85:29)",
              "    at Array.reduce (<anonymous>)",
              "    at JaegerTraceExporter.flattenTags (/Users/itamar/dev/backend/deep-knowledge/node_modules/moleculer/src/tracing/exporters/base.js:80:27)",
              "    at Object.keys.reduce (/Users/itamar/dev/backend/deep-knowledge/node_modules/moleculer/src/tracing/exporters/base.js:85:29)",
              "    at Array.reduce (<anonymous>)",
              "    at JaegerTraceExporter.flattenTags (/Users/itamar/dev/backend/deep-knowledge/node_modules/moleculer/src/tracing/exporters/base.js:80:27)",
              "    at Object.keys.reduce (/Users/itamar/dev/backend/deep-knowledge/node_modules/moleculer/src/tracing/exporters/base.js:85:29)",
              "    at Array.reduce (<anonymous>)"
            ]
          }
        }
      }
    ]
  }
}```

**Comment by icebob** [comment]
Did you add into `tags: {}`? It should upper like me.

**Comment by iatzmon** [comment]
Using the same tags, just added the service property:
```
requestContext.context.span = broker.tracer.startSpan("Execute query", {
    service: svc,
    tags: {
        query: requestContext.request.query,
        variables: requestContext.request.variables
    }
});
```
It works when I remove the service property

**Comment by icebob** [comment]
Ok, I will check tonight.

**Comment by iatzmon** [comment]
thanks!

**Comment by icebob** [comment]
Hmm, it's a bug in the Moleculer Jaeger exporter. I will fix it. But it's a workaround:
```js
requestContext.context.span = broker.tracer.startSpan("Execute query", { 
	service: { fullName: svc.fullName },
	tags: {
		query: requestContext.request.query,
		variables: requestContext.request.variables
	}
});
```

**Comment by iatzmon** [comment]
Looks great, thanks for the help!
And thanks for creating Moleculer, it's truly awesome

**Pull request closed without merging**
